# Generated by Django 6.0.1 on 2026-01-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=90)),
                ('user_image', models.ImageField(default='path/to/placeholder.jpg', upload_to='static/images/')),
            ],
        ),
    ]
