# Generated by Django 6.0.1 on 2026-01-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gurugasspoint', '0002_alter_product_serial_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer_name',
            new_name='customer_name',
        ),
    ]
