# Generated by Django 6.0.1 on 2026-01-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurugasspoint', '0003_rename_customer_name_order_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_image',
            field=models.ImageField(default='path/to/placeholder.jpg', upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='path/to/placeholder.jpg', upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='path/to/placeholder.jpg', upload_to='static/images/'),
        ),
    ]
