# Generated by Django 6.0.1 on 2026-01-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurugasspoint', '0004_customer_customer_image_product_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
    ]
