# Generated by Django 6.0.1 on 2026-01-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurugasspoint', '0005_user_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
