# Generated by Django 6.0.1 on 2026-01-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurugasspoint', '0006_product_barner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barner',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
