# Generated by Django 6.0.1 on 2026-01-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurugasspoint', '0007_remove_product_barner_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='Capture.PNG', upload_to=''),
        ),
    ]
