# Generated by Django 6.0.1 on 2026-01-31 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gurugasspoint', '0009_alter_product_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
