# Generated by Django 6.0.1 on 2026-02-01 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurugasspoint', '0011_cart1_cartitem_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Cart1',
            new_name='Cart',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gurugasspoint.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gurugasspoint.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
