# Generated by Django 6.0.1 on 2026-02-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurugasspoint', '0012_order_rename_cart1_cart_orderitem_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('cell', models.CharField(max_length=11)),
                ('location', models.CharField(max_length=20)),
                ('customer_image', models.ImageField(blank=True, default='customer.png', upload_to='')),
                ('username', models.CharField(max_length=23)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
